newspaper/urls.py
from django.urls import path

from newspaper.views import (
    NewspaperListView,
    NewspaperDetailView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    RedactorDetailView,
    TopicListView,
    TopicCreateView,
    TopicDeleteView,
    TopicUpdateView,
    TopicDetailView,
    NewspaperDeleteView,
    NewspaperCreateView,
    NewspaperUpdateView,

)

urlpatterns = [
    path("", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "article/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "article/<int:pk>/detail",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "article/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "article/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/detail/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "topics/<int:pk>/detail/",
        TopicDetailView.as_view(),
        name="topic-detail"
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="blog-footer cstm-footer mt-4">
  <p>Newspaper agency by
    <a href="https://github.com/Wonsky1" target="_blank">wonsky</a>.
  </p>
</footer>

templates/includes/header.html
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <a class="text-muted" href="https://github.com/Wonsky1" target="_blank">Developed by Wonsky</a>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="/">Newspaper agency</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      {% if user.is_authenticated %}
        <span class="text-muted">Hi, <a class="text-muted" href="{% url 'newspaper:redactor-detail' pk=user.id %}">{{ user.username }}</a></span>
      	<a class="btn btn-sm btn-outline-secondary log-btn" href="{% url 'logout' %}">Logout</a>
      {% else %}
      <a class="btn btn-sm btn-outline-secondary log-btn" href="{% url 'login' %}">Login</a>
      <a class="btn btn-sm btn-outline-secondary log-btn" href="{% url 'newspaper:redactor-create' %}">Sign up</a>
      {% endif %}
    </div>
  </div>
</header>
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <span class="p2"></span>
    <a class="p-2 text-muted" href="{% url 'newspaper:newspaper-list' %}">Articles</a>
    <a class="p-2 text-muted" href="{% url 'newspaper:topic-list' %}">Topics</a>
    <a class="p-2 text-muted" href="{% url 'newspaper:redactor-list' %}">Redactors</a>
    <span class="p2"></span>
  </nav>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
  <input class="btn btn-secondary" type="submit" value="🔍">
</form>