newspaper/urls.py
from django.urls import path

from newspaper.views import (
    NewspaperListView,
    NewspaperDetailView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    RedactorDetailView,
    TopicListView,
    TopicCreateView,
    TopicDeleteView,
    TopicUpdateView,
    TopicDetailView,
    NewspaperDeleteView,
    NewspaperCreateView,
    NewspaperUpdateView,

)

urlpatterns = [
    path("", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "article/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "article/<int:pk>/detail",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "article/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "article/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/detail/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "topics/<int:pk>/detail/",
        TopicDetailView.as_view(),
        name="topic-detail"
    ),
]

app_name = "newspaper"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self) -> str:
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self) -> str:
        return self.username


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField(auto_now_add=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    publishers = models.ManyToManyField(get_user_model())

    class Meta:
        ordering = ("-published_date", )

    def __str__(self) -> str:
        return self.title

newspaper/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from newspaper.models import Newspaper


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self) -> int:
        return cleaned_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self) -> int:
        return cleaned_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


def cleaned_years_of_experience(years_of_experience) -> int:
    if years_of_experience < 0:
        raise ValidationError(
            "Years of experience must be greater or equal than 0"
        )
    if years_of_experience > 100:
        raise ValidationError("Please, provide correct data")
    return years_of_experience


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title..."})
    )

newspaper/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from newspaper.forms import (
    RedactorCreationForm, NewspaperForm,
    RedactorUpdateForm, TopicSearchForm,
    NewspaperSearchForm, RedactorSearchForm
)
from newspaper.models import Newspaper, Topic


class NewspaperListView(generic.ListView):
    model = Newspaper
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperSearchForm(
            initial={"title": title}
        )

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )
        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class RedactorListView(generic.ListView):
    model = get_user_model()
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()

        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorCreateView(generic.CreateView):
    model = get_user_model()
    form_class = RedactorCreationForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()


class TopicListView(generic.ListView):
    model = Topic

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDetailView(LoginRequiredMixin, generic.DetailView):
    model = Topic

templates/newspaper/newspaper_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  {% if user.is_staff %}
    <h1>Delete article {{ newspaper.title }}?</h1>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
      <a href="{% url 'newspaper:newspaper-list' %}" class="btn btn-secondary">Cancel</a>

    </form>
  {% else %}
    <h1>You have not permission to delete this article</h1>
    <a href="{% url 'newspaper:newspaper-list' %}">Go back to articles</a>
  {% endif %}

{% endblock %}

templates/newspaper/newspaper_detail.html
{% extends "base.html" %}
{% block content %}
  <h2 class="pb-3 mb-4 font-italic border-bottom">{{ newspaper.topic.name }}</h2>
  <h1 class="blog-post-title"></h1>
  <div class="blog-post">
    <h2 class="blog-post-title">{{ newspaper.title }}</h2>
    <p class="blog-post-meta">{{ newspaper.published_date }} by
        {% for publisher in newspaper.publishers.all %}
          <a href="#"> {{ publisher.username }}</a>,
        {% endfor %}
    </p>

    <p>{{ newspaper.content }}</p>
  </div>
{% endblock %}

{% block additional %}
  <div style="text-align: right;">
    <a href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}">Update this article</a>
    <a style="color: red" href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}">Delete this article</a>
  </div>
{% endblock %}

templates/newspaper/newspaper_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}
  {% if user.is_staff or not object %}
  <h1>{{ object|yesno:"Update,Create" }} article</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'newspaper:newspaper-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
  {% else %}
    <h1>You have not permission to update article</h1>
    <a href="{% url 'newspaper:newspaper-list' %}">Go back to articles</a>
  {% endif %}
{% endblock %}

templates/newspaper/newspaper_list.html
{% extends "base.html" %}
{% block content %}
  {% include "includes/search_form.html" %}
  <div class="row mb-2">
    {% for article in page_obj %}
      <div class="col-md-6">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
          <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary"><a href="{% url 'newspaper:topic-detail' pk=article.topic.id %}">{{ article.topic.name }}</a></strong>
            <h3 class="mb-0">
              <a class="text-dark" href="{% url 'newspaper:newspaper-detail' pk=article.id %}">{{ article.title }}</a>
            </h3>
            <div class="mb-1 text-muted">{{ article.published_date }}</div>
            <p class="card-text mb-auto">{{ article.content|slice:":120"  }}...</p>
            <a href="{% url 'newspaper:newspaper-detail' pk=article.id %}">Continue reading</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}
{% block additional %}
  <div style="text-align: center;">
    <a style="" href="{% url 'newspaper:newspaper-create' %}">Post new article</a>
  </div>
{% endblock %}

templates/newspaper/redactor_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  {% if user.is_staff %}
    <h1>Delete redactor {{ redactor.username }}?</h1>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
      <a href="{% url 'newspaper:topic-list' %}" class="btn btn-secondary">Cancel</a>

    </form>
  {% else %}
    <h1>You have not permission to delete this redactor</h1>
    <a href="{% url 'newspaper:redactor-list' %}">Go back to redactors</a>
  {% endif %}
{% endblock %}

templates/newspaper/redactor_detail.html
{% extends "base.html" %}
{% block content %}
  <h1>Redactor detail</h1>
  <div class="row">
    <div class="col-lg-4">
      <div class="card mb-4">
        <div class="card-body text-center">
          <h5 class="my-3">{{ redactor.username }}</h5>
        </div>
      </div>
      <div class="d-flex justify-content-center mb-2">
        <a class="btn btn-primary" href="{% url 'newspaper:redactor-update' pk=redactor.id %}">Update redactor</a>
        <a class="btn btn-danger" href="{% url 'newspaper:redactor-delete' pk=redactor.id %}">Delete redactor</a>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Firstname</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">
                {% if redactor.first_name %}
                  {{ redactor.first_name }}
                {% else %}
                  Not provided
                {% endif %}
              </p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Lastname</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">
                {% if redactor.last_name %}
                  {{ redactor.last_name }}
                {% else %}
                  Not provided
                {% endif %}
              </p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Email</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">
                {% if redactor.email %}
                  {{ redactor.email }}
                {% else %}
                  Not provided
                {% endif %}
              </p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Years of experience</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">
                {{ redactor.years_of_experience }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/newspaper/redactor_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}
  {% if user.is_staff or not object %}
  <h1>{{ object|yesno:"Update,Create" }} redactor {{ redactor.username }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'newspaper:redactor-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
  {% else %}
    <h1>You have not permission to update redactor</h1>
    <a href="{% url 'newspaper:redactor-list' %}">Go back to redactors</a>
  {% endif %}
{% endblock %}

templates/newspaper/redactor_list.html
{% extends "base.html" %}

{% block content %}
  {% include "includes/search_form.html" %}
  <h1>Redactors:</h1>
  {% for redactor in redactor_list %}
    <div class="btn">
      <div class="row">
        <div class="col-md-9">
          <a class="p-2 text-muted" href="{% url 'newspaper:redactor-detail' pk=redactor.id %}" class="forum-item-title">{{ redactor.username }}</a>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

templates/newspaper/topic_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  {% if user.is_staff %}
    <h1>Delete topic {{ topic.name }}?</h1>
    <p>If you delete this topic, all articles related to it will be deleted too!</p>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Yes" class="btn btn-danger">
      <a href="{% url 'newspaper:topic-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
  {% else %}
    <h1>You have not permission to delete this topic</h1>
    <a href="{% url 'newspaper:topic-list' %}">Go back to topics</a>
  {% endif %}
{% endblock %}

templates/newspaper/topic_detail.html
{% extends "base.html" %}
{% block content %}
  <h1>Topic {{ topic.name }}</h1>
{% endblock %}

{% block additional %}
  <div style="text-align: right;">
    <a href="{% url 'newspaper:topic-update' pk=topic.id %}">Update this topic</a>
    <a style="color: red" href="{% url 'newspaper:topic-delete' pk=topic.id %}">Delete this topic</a>
  </div>
{% endblock %}

templates/newspaper/topic_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}

{% block content %}
  {% if user.is_staff or not object %}
    <h1>{{ object|yesno:"Update,Create" }} topic</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
      <a href="{% url 'newspaper:topic-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
  {% else %}
    <h1>You have not permission to update topic</h1>
    <a href="{% url 'newspaper:topic-list' %}">Go back to topics</a>
  {% endif %}
{% endblock %}

templates/newspaper/topic_list.html
{% extends "base.html" %}
{% block content %}
  {% include "includes/search_form.html" %}
  <h1>Topics:</h1>
  {% for topic in topic_list %}
    <div class="btn">
      <div class="row">
        <div class="col-md-9">
          <a class="p-2 text-muted" href="{% url 'newspaper:topic-detail' pk=topic.id %}" class="forum-item-title">{{ topic.name }}</a>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

{% block additional %}
  <div style="text-align: center;">
    <a style="" href="{% url 'newspaper:topic-create' %}">New topic</a>
  </div>
{% endblock %}